### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by adunkman** [adunkman/dctech.tv#1]
The idea is still forming, but I’d like to see if the interest is there to professionally record tech talks presented in the DC area. 

What would we need to make that happen? I’ll do some thinking on the subject.

**Comment by SteveChenDC** [comment]
That sounds really cool

**Comment by adunkman** [comment]
I just ran into @rektide and chatted a bit about this, and he mentioned @johnelliott was talking about something about this. Just summoning you in case you’re interested further. :)

**Comment by johnelliott** [comment]
@adunkman I think this is the idea of a webRTC recording app, but mobile safari lagging put me off working on something like that. Maybe in a year or so I'll be worth engaging.

**Comment by adunkman** [comment]
An update! I’m making this happen! 

![it’s happening, isn’t it!](https://media.giphy.com/media/lkK7hFTOp1s4g/giphy.gif)

I’ve pushed a teaser site out to https://www.dctech.tv and have secured the money needed to purchase equipment.
