### ISSUE TITLE
Logo design.

### ISSUE THREAD

**Issue by adunkman** [adunkman/dctech.tv#3]
We’ll need a logo for this thing, and probably some fancy motion graphics to kick off videos. I’m considering hiring someone, since professionals are professional maybe? 

DC has a problem (problem?) with rapid turnover. I’d like to capture the idea of the historical side of DC, rather than trying to be #hip. As this whole thing is about amplifying people who aren’t white guys (sorry white guys, but you’re secondary this time around), I’d rather not reference the lineage of white guys that are Presidents of the United States. No busts of Lincoln here.

When I think of DC, I think of:
- Townhouses
- The Capitol Dome
- Cool “Disco” Dan
- Black Broadway
- Go-go music
- Streetcars and public transportation
- Bricked sidewalks and stone curbs

I don’t want to emphasize the “tech” or “tv” part of it too much — neither of them are particularly inspiring to me. I actually called this “dctechvideos” at first, which seems more fitting than “tv” — but “tv” is a top-level domain. 😄 

What do you think about when you think of dctech.tv?

**Comment by adunkman** [comment]
I’ve done a bit of chatting and sketching with @AlexDaii (I think he has plans to post some of the sketches here), but I took a few minutes and did some thinking today independently. I think overall my desire to stick to simple shapes has lead me away from a lot of what I said above (whoops) and I sketched up a few ideas.

Clapperboard:

![image](https://user-images.githubusercontent.com/14930/34956335-97e68a86-f9f6-11e7-8c32-b3b86cb7e341.png)

Flag stripes:

![image](https://user-images.githubusercontent.com/14930/34956787-afd07f60-f9f8-11e7-9ce3-825a09625501.png)

**Comment by jkeam** [comment]
The advantage of the latter is that it has the actual url and looks very professional.
The advantage of the former is that it more clearly conveys what this organization does. That clapper seems to hit all the right connotations.

**Comment by jkeam** [comment]
Also you might checkout https://www.fiverr.com/ for some quick/cheap/pretty effective outsourcing.

**Comment by AlexDaii** [comment]
I like your 2nd design with flag.

**Comment by AlexDaii** [comment]
Here are some other suggestions.
![img_6562](https://user-images.githubusercontent.com/30300997/34958749-30e4fdd0-fa01-11e7-868c-f11a9ff82ceb.JPG)

**Comment by adunkman** [comment]
I do really like the clapperboard design — I think it has the right connotations. I don’t like that it doesn’t stand alone (I’d like it to reference the full URL). 

I’ll play with a few variants and see if I can make it work with the full URL.

**Comment by adunkman** [comment]
Longer: 

![image](https://user-images.githubusercontent.com/14930/35024009-440b398c-fb0b-11e7-94e9-7bde60bc6e31.png)

Badge:

![image](https://user-images.githubusercontent.com/14930/35024019-52403fac-fb0b-11e7-8333-03b4ba5e325a.png)

Smaller text, at an angle:

![image](https://user-images.githubusercontent.com/14930/35024023-5c8b8bba-fb0b-11e7-93e9-33553b90ddef.png)

Smaller text, straight:

![image](https://user-images.githubusercontent.com/14930/35024028-65853766-fb0b-11e7-9897-664eb2bb6a93.png)

**Comment by jkeam** [comment]
i like the last two

**Comment by adunkman** [comment]
Slightly larger shape, slightly smaller text:

![image](https://user-images.githubusercontent.com/14930/35024265-86e3fa18-fb0c-11e7-8817-29f9fd488567.png)

Smaller clapperboard:

![image](https://user-images.githubusercontent.com/14930/35024289-9dfbabf6-fb0c-11e7-8651-3da9731a5734.png)

**Comment by adunkman** [comment]
I’m not a huge fan of the angled text, I think it makes the logo feel unbalanced, like it’s about to fall over backwards. I think I’d stick with level text.

**Comment by adunkman** [comment]
I think I might have a final one for now:

![image](https://user-images.githubusercontent.com/14930/35024446-81b8c630-fb0d-11e7-8309-cae2515942b0.png)

I thinned out the … clapper? the top part. Maybe it still looks too rectangular though… let’s compare it to one that’s more square: 

![image](https://user-images.githubusercontent.com/14930/35024491-bcacf1bc-fb0d-11e7-9be5-e1d1841c1ab7.png)

Thoughts on just these two compared with each other @jkeam and @AlexDaii?

**Comment by jkeam** [comment]
i prefer square shapes over rectangles.

**Comment by jkeam** [comment]
_hip to be a square_

**Comment by adunkman** [comment]
Upon looking at it this morning, I went with an earlier variant which has the shape I’m looking for:

![image](https://user-images.githubusercontent.com/14930/35049607-8f3a1758-fb6e-11e7-8305-382e5580235d.png)

I’m going to consider this issue closed, and open a separate one for intro and outro clips.

**Comment by adunkman** [comment]
Added a variant for small sizes (like the Twitter avatar): 

![circular](https://user-images.githubusercontent.com/14930/35051046-50735684-fb72-11e7-8223-04575b4d9bd3.png)

Here’s what it looks like in context:

![image](https://user-images.githubusercontent.com/14930/35051072-614bd210-fb72-11e7-99d5-1b43e6baff17.png)

**Comment by adunkman** [comment]
One last comment — if you find yourself here on the issue and are interested in the resulting files, they’re located at https://github.com/adunkman/dctech.tv/tree/master/logos.
